name: Build and Push Image and update gitops

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }} #us-east-1
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }} #753675398055.dkr.ecr.us-east-1.amazonaws.com/wordpress-app
  GITOPS_REPO: ${{ secrets.GITOPS_REPO }}
  GITOPS_BRANCH: ${{ secrets.GITOPS_BRANCH }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare image tag
        id: prepare_image
        run: |
          IMAGE_TAG="r${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Clone GitOps repository
        run: |
          git clone --branch "${GITOPS_BRANCH}" \
            "https://${{ secrets.GITOPS_PAT }}@${GITOPS_REPO#https://}" \
            gitops          

      - name: Update newTag to latest using sed
        run: |
          cd gitops
          FILE="overlays/prod/kustomization.yaml"
          
          # Replace first occurrence of newTag
          sed -i '0,/newTag:/s/newTag:.*/newTag: "latest"/' "$FILE"

      - name: Commit and push GitOps change
        run: |
          cd gitops
          git config user.email "actions@github.com"
          git config user.name "github-actions"

          git add overlays/prod/kustomization.yaml

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Deploy latest image"
            git push origin "${GITOPS_BRANCH}"
          fi



          